services:
  - type: web
    name: partyservice-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn server:app
    envVars:
      - key: BREVO_API_KEY
        sync: false
      - key: EMAIL_TO
        value: deine@email.de
      - key: SENDER_NAME
        value: Partyservice Alexa
      - key: SENDER_EMAIL
        value: noreply@partyservice.com
